baseURL: https://benrwoodard.com
title: 'BenRWoodard.com'
copyright: Copyright © 2021, Ben R Woodard; all rights reserved.
paginate: 2
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
footnoteReturnLinkContents: ^
DisqusShortname: ''
theme: hugo-theme-chunky-poster
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: categories
      name: Categories
      url: /categories
      weight: 4
    - identifier: about
      name: About
      url: /about/
      weight: 5
    - identifier: adobeanalyticsr
      name: adobeanalyticsr
      url: https://adobeanalyticsr.com
      weight: 2
    - identifier: statsearchanalyticsr
      name: statsearchanalyticsr
      url: https://statsearchanalyticsr.com
      weight: 3
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
params:
  author: Ben R Woodard
  comments: 
    enable: true
  commento:
    enable: no
    url: https://commento.io
  customCSS: ["custom.css"]
  customJS: []
  dateFormat: January 2, 2006
  subheader: A simple blog about analytics and R
  description: I'm a data scientist at Search Discovery where I use R to solve problems and answer questions around digital marketing analytics.
  homepageImage: /images/bringcoffee.png
  gtm_id: GTM-WLBMNP
  gtm_datalayer: basic
  prismJS:
    enable: yes
    theme: ''
  share: yes
  showLanguageSwitcher: no
  social:
    email: benrwoodard@gmail.com
    github: https://github.com/benrwoodard
    linkedin: https://linkedin.com/in/benrwoodard
    rss: yes
    twitter: https://twitter.com/benrwoodard
services:
  instagram:
    disableInlineCSS: yes
  twitter:
    disableInlineCSS: yes
ignoreErrors: ["error-remote-getjson"]
markup:
  highlight:
    codeFences: no
  goldmark:
    renderer:
      unsafe: true
