baseURL: /
title: 'Ben R Woodard'
copyright: Copyright © 2021, Ben R Woodard; all rights reserved.
paginate: 2
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
footnoteReturnLinkContents: ^
googleAnalytics: UA-XXXX
DisqusShortname: ''
theme: hugo-theme-chunky-poster
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags
      weight: 0
    - identifier: about
      name: About
      url: /about/
      weight: 0
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
params:
  author: Ben R Woodard
  commento:
    enable: yes
    url: https://commento.io
  customCSS: []
  customJS: []
  dateFormat: January 2, 2006
  description: A blog about life, analytics and R </br><i>but mainly about R</i>
  homepageImage: /images/bringcoffee.png
  prismJS:
    enable: yes
    theme: ''
  share: yes
  showLanguageSwitcher: no
  social:
    email: benrwoodard@gmail.com
    github: https://github.com/benrwoodard
    linkedin: https://linkedin.com/in/benrwoodard
    rss: yes
    twitter: https://twitter.com/benrwoodard
markup:
  highlight:
    codeFences: no
services:
  instagram:
    disableInlineCSS: yes
  twitter:
    disableInlineCSS: yes
ignoreErrors: ["error-remote-getjson"]
