baseURL: https://benrwoodard.com
title: 'BenRWoodard.com'
copyright: Copyright © 2021, Ben R Woodard; all rights reserved.
paginate: 2
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
footnoteReturnLinkContents: ^
DisqusShortname: ''
theme: hugo-theme-chunky-poster
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags
      weight: 3
    - identifier: about
      name: About
      url: /about/
      weight: 4
    - identifier: adobeanalyticsr
      name: adobeanalyticsr
      url: https://adobeanalyticsr.com
      weight: 2
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
params:
  author: Ben R Woodard
  enableGitalk: true
  commento:
    enable: no
    url: https://commento.io
  customCSS: ["custom.css"]
  customJS: []
  dateFormat: January 2, 2006
  subheader: A simple blog about analytics and R
  description: I'm a data scientist at Search Discovery where I use R to solve problems and answer questions around digital marketing analytics.
  homepageImage: /images/bringcoffee.png
  gtm_id: GTM-WLBMNP
  gtm_datalayer: basic
  prismJS:
    enable: yes
    theme: ''
  share: yes
  showLanguageSwitcher: no
  social:
    email: benrwoodard@gmail.com
    github: https://github.com/benrwoodard
    linkedin: https://linkedin.com/in/benrwoodard
    rss: yes
    twitter: https://twitter.com/benrwoodard
  gitalk:
    clientID: 'Iv1.678c10057628e8ba' # Your client ID
    clientSecret: f397def477930616e0588272ad243c9f0eeb4c8d # Your client secret
    repo: benrwoodard_com # The repo to store comments
    owner: benrwoodard # Your GitHub ID
    admin: benrwoodard # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id: location.pathname # The unique id of the page.
    labels: gitalk # Github issue labels. If you used to use Gitment, you can change it
    perPage: 15 # Pagination size, with maximum 100.
    pagerDirection: last # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually: false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode: false # Enable hot key (cmd|ctrl + enter) submit comment.
services:
  instagram:
    disableInlineCSS: yes
  twitter:
    disableInlineCSS: yes
ignoreErrors: ["error-remote-getjson"]
markup:
  highlight:
    codeFences: no
  goldmark:
    renderer:
      unsafe: true
