baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Ben R Woodard"
theme = "cupper-hugo-theme-master"
googleAnalytics = "UA-12086340-1"
disqusShortname = "benrwoodard-com"
enableGitInfo = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Doing the hard things that others say is impossible."
  homeMetaContent = "Analytics, Family and Farm"
  footer = "Made with RStudio in Anna, TX."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-20"
  codePenUser = "someUser"
  katex = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5