---
title: Now On CRAN adobeanalyticsr
author: Ben R Woodard
date: '2021-03-01'
slug: now_on_cran_adobeanalyticsr
categories: R
tags: 
  - package 
  - rsitecatalyst
  - adobe analytics
images: ['adobeanalyticsr_logo2.png']
authors: 
- benrwoodard
---

I'm super excited to announce that adobeanaltyicsr v0.1.5 is now available on CRAN!  adobeanalyticsr is an R client for the new 'Adobe Analytics' API 2.0 and had a lot of great features that I believe will help data analysts do their jobs better.

<!--more-->  

The new adobeanalyticsr package was an open source project that started when [Tim Wilson](https://twitter.com/tgwilson) began exploring functions that would pull data using the new API 2.0. This API has already been making waves in the analytics industry since it's introduction via the Analysis Workspace user interface a few years back. 

I believe it is critical to thank Randy for the work he put in to creating and maintaining RSiteCatalyst. His development work on the old Adobe Analytics R package quite literally changed the way I did my job and the questions I could ask. I truly hope that adobeanalyticsr can continue the level of excellence that Randy instilled in RSiteCatalyst.

Here are a few of the features the new R package for Adobe Anaytics affords us as analysts over the old API:

* Up to 20 dimensions at a time.
  * The old API 1.4 had a limit of 4
  * The API 2.0 doesn't have any restrictions but the package does. This limitation is only temporary
while we develop the package.

* Faster API calls.
  * The old API used a queue process.
  * The new API has no queue but needs recursive data requests to pull breakdown reports.
  
* Future functionality
  * The old API has not been developed in quite a while
  * The new API is getting a lot of focus since it is the backbone of Analysis Workspace.
  
Those three distinctions are just a few of the many benefits of using the new api. Now with the package being included in CRAN, everyone can easily begin using the new powerful API.
```r
install.packages('adobeanalyticsr')
library(adobeanalyticsr)
```

While this is a great milestone that has been in the works for about a year and a half, it is just the beginning.  Development work has already begun on the next itteration of the package.  We are looking for more community feedback and would love to hear your thoughts on improvements and enhancements to the package.  Checkout [AdobeAnalyticsR.com](https://adobeanalyticsr.com) for more information and a link to the github repo where you can submit issues and submit enhancments.





